### ISSUE TITLE
Page text alignment is off

### ISSUE THREAD

**Issue by svmelton** [BCDigSchol/exhibits-omeka-theme#11]
On the About page, the text is misaligned:
![screen shot 2017-12-11 at 11 28 18 am](https://user-images.githubusercontent.com/7232545/33841721-810f6b62-de66-11e7-8d19-0b25b64ef9dd.png)

**Comment by svmelton** [comment]
I deleted the about page, but I wanted to flag this, as text alignment seems to be off in all simple pages.

**Comment by Otterfan** [comment]
I'm making a standard template for simple pages—just a plain white box that holds well-set type. We can style it on a case-by-case basis.
